weather_app/weather/urls.py
from django.urls import path
from . import views

app_name = 'weather'

urlpatterns = [
    path('task/<int:x>/<int:y>', views.task, name="task1"), 
    path('',views.index, name="index"),
    path('delete/<city_name>/', views.delete_city, name='delete_city'),
    path('github/',views.github, name="github"),
    path('user_search/', views.user_search, name="user_search"),
    path('view_weather/', views.view_weather, name="view_weather"),
    path('top_three/', views.top_three, name="top_three"),
    path('search/', views.weather_search, name="search"), 
]

weather_app/weather_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('weather.urls')),
]

weather_app/weather/models.py
from django.db import models

class City(models.Model):
    name = models.CharField(max_length=30)
    count = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Cities'

weather_app/weather/forms.py
from django.forms import ModelForm, TextInput
from .models import City 

class CityForm(ModelForm):
    class Meta:
        model = City 
        fields = ['name']
        widgets = {'name' : TextInput(attrs={'class' : 'input', 'placeholder' : 'City Name'})}

weather_app/weather/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.http import JsonResponse
import requests 
from .models import City
from .forms import CityForm
from .task1 import Task1

#Task 1,2 using dynamic url
def task(request, x, y):
    data = Task1(x,y)
    print(data)
    return JsonResponse(Task1(x,y), safe=False)

# Searching and Adding Weather according to City To Database using POST request
def index(request):
    url = 'https://api.openweathermap.org/data/2.5/weather?q={}&units=metric&appid=d9f018ab094f5f7a34df0ec41f79c368'

    err_msg = ''
    message = ''
    message_class = ''

    if request.method == 'POST':
        form = CityForm(request.POST)
        if form.is_valid():
            new_city = form.cleaned_data['name']
            existing_city_count = City.objects.filter(name=new_city).count()
            
            if existing_city_count == 0:
                r = requests.get(url.format(new_city)).json()

                if r['cod'] == 200:
                    form.save()
                else:
                    err_msg = 'No Such City Found!'
            else:
                city_names = City.objects.filter(name=new_city)
                if city_names.exists():
                    for city_name in city_names:
                        total = int(city_name.count) + 1
                    city_names.update(count=total)
                err_msg = 'City Already Exists!!'
        if err_msg:
            message = err_msg
            message_class = 'is-danger'
        else:
            message = 'City added successfully!'
            message_class = 'is-success'
    form = CityForm()

    cities = City.objects.all()
    weather_data = []
    for city in cities:
        res = requests.get(url.format(city)).json()
        city_weather = {
            'city' : city.name,
            'temperature' : res['main']['temp'],
            'description' : res['weather'][0]['description'],
            'icon' : res['weather'][0]['icon'],
        }
        weather_data.append(city_weather)

    total = City.objects.all().count()
    context = {
        'weather_data' : weather_data,
        'form' : form,
        'message' : message,
        'message_class' : message_class,
        'total': total,
    }
    return render(request, 'weather/index.html', context)

# Deleting particular city from DB
def delete_city(request, city_name):
    City.objects.get(name=city_name).delete() 
    return redirect('/')

# Weather of the city search form for GET request
def weather_search(request):
    return render(request, 'weather/weather.html')

# Increasing the count if the searched city already exists in the DB
def view_weather(request):
    if request.method == 'GET':
        city = request.GET['city']
    url = 'https://api.openweathermap.org/data/2.5/weather?q={}&units=metric&appid=d9f018ab094f5f7a34df0ec41f79c368'
    res = requests.get(url.format(city)).json()
    city_weather = {
            'city' : city,
            'temperature' : res['main']['temp'],
            'description' : res['weather'][0]['description'],
        }
    context = {
        'city_weather' : city_weather
    }
    if res['cod'] == 200:
        city_names = City.objects.filter(name=city)
        all_cities = City.objects.all()
        if city_names.exists():
            for city_name in city_names:
                total = int(city_name.count) + 1
            city_names.update(count=total)
    return render(request, 'weather/weather.html', context)

# Getting the top_three most searched cities
def top_three(request):
    url = 'https://api.openweathermap.org/data/2.5/weather?q={}&units=metric&appid=d9f018ab094f5f7a34df0ec41f79c368'
    cities = City.objects.all().order_by('-count')[:3]
    res1 = requests.get(url.format(cities[0])).json()
    res2 = requests.get(url.format(cities[1])).json()
    res3 = requests.get(url.format(cities[2])).json()
    city_one = {
        'city' : cities[0].name,
        'temperature' : res1['main']['temp'],
        'description' : res1['weather'][0]['description'],
    }
    city_two = {
        'city' : cities[1].name,
        'temperature' : res2['main']['temp'],
        'description' : res2['weather'][0]['description'],
    }
    city_three = {
        'city' : cities[2].name,
        'temperature' : res3['main']['temp'],
        'description' : res3['weather'][0]['description'],
    }
    context = {
        'city_one' : city_one,
        'city_two' : city_two,
        'city_three' : city_three,
        'cities': cities
    }
    return render(request, 'weather/top_three.html', context)

# search form for entering the username using GET request
def user_search(request):
    return render(request, 'weather/github.html')

# getting github user information based on the GET search request
def github(request):
    if request.method == 'GET':
        username = request.GET['username']
    url = 'https://api.github.com/users/{}'
    res = requests.get(url.format(username)).json()
    user_info = {
        'name' : res['name'],
        'image' : res['avatar_url'],
        'link' : res['url'],
        'location' : res['location'],
        'bio' : res['bio'],
        'public_repos' : res['public_repos'],
        'followers' : res['followers'],
        'following' : res['following'], 
        'created' : res['created_at'][0:10],
        'update' : res['updated_at'][0:10],
    }
    context = {
        'user_info' : user_info,
    }
    return render(request, 'weather/github.html', context)

weather_app/weather/templates/weather/github.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>           
    <title>Github</title>
    <style>
        #follow{
            display: flex;
            text-align: center;
            justify-content: center;
        }
        #content{
            display: flex;
            flex-direction: column;
            justify-content: center;
            text-align: center;
        }
    </style>
</head>
<body>
    <nav>
        <div class="nav-wrapper">
          <a href="{% url 'weather:user_search' %}" class="brand-logo">Github</a>
          <ul id="nav-mobile" class="right">
            <li><a href="{% url 'weather:index' %}">Weather</a></li>
          </ul>
        </div>
    </nav>
    <div class="container">
        <div class="form row">
            <form class="col s12" method="GET" action="{% url 'weather:github' %}">
                {% csrf_token %}
                <div class="input-field">
                    <input type="text" name="username" placeholder="Enter GitHub Username">
                </div>
            </form>
        </div>
        {% if user_info %}
            <div class="row">
                <div class="col s3"></div>
                <div class="col s6">
                    <div class="card">
                        <div class="card-image">
                            <img src="{{ user_info.image }}">
                        </div>
                            <div class="card-content" id="content">
                                <h2>{{ user_info.name }}</h2>
                                {% if user_info.location %}
                                    <h5>Location: {{ user_info.location }}</h5>
                                {% endif %}
                                {% if user_info.bio %}
                                    <h6>{{ user_info.bio }}</h6>
                                {% endif %}
                                <h5>Public Repositories : {{ user_info.public_repos }}</h5>
                                <div class="follow" id="follow">
                                    <h5>Followers : {{ user_info.followers }}</h5>
                                    <h5 style="margin-left: 10px;">Following : {{ user_info.following }}</h5>
                                </div>                         
                                <h5>Created : {{ user_info.created }}</h5>
                                <h5>Updated : {{ user_info.update }}</h5>
                            </div>
                            <div class="card-action"  id="content">
                                <a href="{{ user_info.link }}">Github Link</a>
                            </div>
                        </div>
                    </div>
                <div class="col s3"></div>
        </div>
        {% endif %}
    </div>
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>
</body>
</html>

weather_app/weather/templates/weather/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Weather</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />
</head>

<body>
    <section class="hero is-primary">
            <div class="container">
                <nav class="navbar" role="navigation" aria-label="main navigation">
                    <div class="navbar-brand">
                      <a class="navbar-item" href="{% url 'weather:index' %}">
                        <h2>Weather</h2>
                      </a>
                    </div>                  
                    <div class="navbar-end">
                        <div class="navbar-item">
                          <div class="buttons">
                            <h2><a href="{% url 'weather:user_search' %}" >Github</a></h2>
                            <h2><a href="{% url 'weather:search' %}" style="margin-left: 7px;">Weather-Search</a></h2>
                            <h2><a href="{% url 'weather:top_three' %}" style="margin-left: 7px;">Top-Three</a></h2>
                          </div>
                        </div>
                      </div>
                    </div>
                </nav>
            </div>
    </section>
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="field has-addons">
                            <div class="control is-expanded">
                                {{ form.name }}
                            </div>
                            <div class="control">
                                <button type="submit" class="button is-info">
                                    Add City
                                </button>
                            </div>
                        </div>
                        {% if message %}
                            <div class="notification {{ message_class }}">{{ message }}</div>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
                    <h5 class="title text-center">
                        Total Cities Added : {{ total }}
                    </h5>
                    {% for city_weather in weather_data %}
                    <div class="box">
                        <article class="media">
                            <div class="media-left">
                                <figure class="image is-50x50">
                                    <img src="http://openweathermap.org/img/w/{{ city_weather.icon }}.png" alt="Image">
                                </figure>
                            </div>
                            <div class="media-content">
                                <div class="content">
                                    <p>
                                        <span class="title">{{ city_weather.city }}</span>
                                        <br>
                                        <span class="subtitle">{{ city_weather.temperature }} °C</span>
                                        <br> {{ city_weather.description }}
                                    </p>
                                </div>
                            </div>
                            <div class="media-right">
                                <a href="{% url 'weather:delete_city' city_weather.city %}">
                                    <button class="delete"></button>
                                </a>
                            </div>
                        </article>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
    <footer class="footer">
    </footer>
</body>

</html>

weather_app/weather/templates/weather/top_three.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">         
    <title>Weather_Top_Three</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'weather:index' %}">Weather</a>
        <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'weather:index' %}">Weather<span class="sr-only"></span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'weather:search' %}">Weather-Search<span class="sr-only"></span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'weather:top_three' %}">Top Three</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        <div class="row mt-3">
            <div class="col-sm-4 m-auto card">
                <h4 class="text-center"><u>Three Most Searched Cities:</u></h4>
                <div class="text-center">
                    {% for city in cities %}
                    <h4>{{ city.name }}</h4>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-sm-6 m-auto">
                <div class="card text-center bg-primary">
                    <h1>{{ city_one.city }}</h1>
                    <h6>{{ city_one.temperature }}°C</h6>
                    <h6>{{ city_one.description }}</h6>
                </div>
            </div>
        </div>
        <div class="row  mt-3">
            <div class="col-sm-6 m-auto">
                <div class="card text-center bg-success">
                    <h1>{{ city_two.city }}</h1>
                    <h6>{{ city_two.temperature }}°C</h6>
                    <h6>{{ city_two.description }}</h6>
                </div>
            </div>
        </div>
        <div class="row  mt-3">
            <div class="col-sm-6 m-auto">
                <div class="card text-center bg-danger">
                    <h1>{{ city_three.city }}</h1>
                    <h6>{{ city_three.temperature }}°C</h6>
                    <h6>{{ city_three.description }}</h6>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

weather_app/weather/templates/weather/weather.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">         
    <title>Weather_GET</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'weather:index' %}">Weather</a>
        <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'weather:index' %}">Weather<span class="sr-only"></span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'weather:search' %}">Weather-Search<span class="sr-only"></span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'weather:top_three' %}">Top Three</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        <div class="form row mt-3">
            <form method="GET" class="col-sm-6 m-auto" action="{% url 'weather:view_weather' %}">
                {% csrf_token %}
                <input class="form-control mr-sm-2" name="city" type="search" placeholder="Search">
            </form>
        </div>
        {% if city_weather %}
        <div class="row">
            <div class="col-sm-4 m-auto">
                <div class="text-center card mt-3 bg-success">
                    <h1>{{ city_weather.city }}</h1>
                    <h3>{{ city_weather.temperature }}°C</h3>
                    <h3>{{ city_weather.description }}</h3>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>